import streamlit as st


def render_hotspot_alerts():

    st.title("🗺️ Hotspot Alerts")

    st.caption(
        "Important future-risk predictions generated by CleanWatch AI"
    )

    alerts = [
        {
            "location": "Block B Pathway",
            "risk": "HIGH",
            "score": "78%"
        },
        {
            "location": "Cafeteria Entrance",
            "risk": "HIGH",
            "score": "74%"
        }
    ]

    for alert in alerts:

        with st.container(border=True):

            st.subheader(
                alert["location"]
            )

            col1, col2 = st.columns(2)

            col1.metric(
                "Risk",
                alert["risk"]
            )

            col2.metric(
                "Prediction Score",
                alert["score"]
            )

            st.write(
                "This location has been identified by the "
                "CleanWatch hotspot prediction system as a "
                "potential high-risk area."
            )