import streamlit as st


def render_evidence_viewer():

    st.title("🔍 Evidence Viewer")

    st.caption(
        "Evidence generated by the AI event reconstruction pipeline"
    )

    incident_id = st.selectbox(
        "Incident",
        [
            "INC-001",
            "INC-002",
            "INC-003"
        ]
    )

    st.subheader("Incident Evidence")

    st.info(
        "Evidence frames and video clips generated by the AI "
        "pipeline will appear here."
    )

    col1, col2, col3 = st.columns(3)

    with col1:
        st.write("**Frame 1 — Hold**")
        st.empty()

    with col2:
        st.write("**Frame 2 — Release**")
        st.empty()

    with col3:
        st.write("**Frame 3 — Land**")
        st.empty()

    st.divider()

    st.subheader("AI Reasoning")

    st.write(
        "Person was tracked while holding the detected waste."
    )

    st.write(
        "Waste was released from the person's interaction zone."
    )

    st.write(
        "Waste remained on the ground after the person moved away."
    )

    st.metric(
        "Evidence Confidence",
        "94%"
    )